version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build:
      context: ./backend
    container_name: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - "3030:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - WDS_SOCKET_PORT=0
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4040:3000"
    depends_on:
      - backend

volumes:
  db_data:
