version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      dockerfile: production.Dockerfile
    container_name: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 52145 -b '0.0.0.0'"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/dinnertime
      - SECRET_KEY_BASE=69782b185cf994696b846e43b8e26a6c9f724905c74bf7556162c5a18cd17edc68a702ffbd0df7e855e2f4c6cf71bf68c794741c9234841f45446c3679bd8e6d
    ports:
      - "52145:52145"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      target: production
    container_name: frontend
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
