version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    container_name: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - "3030:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      target: production
    container_name: frontend
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d/
    ports:
      - "4040:80"
    depends_on:
      - backend

volumes:
  db_data:
