version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
    container_name: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/dinnertime
    volumes:
      - ./backend:/app
    ports:
      - "3030:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      target: development
    container_name: frontend
    environment:
      - WDS_SOCKET_PORT=0
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4040:3000"
    depends_on:
      - backend

volumes:
  db_data:
